### ISSUE TITLE
Exchange Button Doesn't Work after 2nd Click

### ISSUE THREAD

**Issue by hernands24** [hilerio23/TheOfficalScrabbleGame#10]
The exchange button does not work after clicking it 2 times. The application seems to pause and none of the other buttons work afterwards. If you click the play word button, the application closes. No tiles will be placed and none of the tiles change or are exchanged.
	Steps to recreate:
-	Start game
-	Click exchange (2 times or more)
Below is what is printed out to the Logcat, as you can see nothing is occurring just attempts to the GameHumanPlayer class.

**Comment by samonew** [comment]
This would be resolved with the addition of the pop-up notifications because this is an International feature that notifies the game that there are no more valid moves
